# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: Microsoft.VCRedist.2015+.x64
PackageVersion: 14.50.35719.0
PackageLocale: zh-TW
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/zh-tw
PublisherSupportUrl: https://support.microsoft.com/
PrivacyUrl: https://privacy.microsoft.com/privacystatement
Author: Microsoft Corporation
PackageName: Microsoft Visual C++ 可再發行套件 v14 (x64)
PackageUrl: https://learn.microsoft.com/zh-tw/cpp/windows/latest-supported-vc-redist
License: Proprietary (免費軟體)
LicenseUrl: https://www.microsoft.com/legal/terms-of-use
Copyright: © Microsoft Corporation
CopyrightUrl: https://www.microsoft.com/zh-tw/legal/intellectualproperty/trademarks
ShortDescription: Visual C++ 可轉散發套件會安裝 Microsoft C 和 C++ 執行階段程式庫。 許多使用 Microsoft C++ （MSVC） 建置工具建置的應用程式都需要這些程式庫。 如果您的應用程式是使用這些程式庫建置的，則必須在目標系統上與應用程式一起安裝至少和建置應用程式時使用的建置工具一樣新版的 Microsoft Visual C++ 可轉散發套件。
Description: Visual C++ 可轉散發套件會安裝 Microsoft C 和 C++ 執行階段程式庫。 許多使用 Microsoft C++ （MSVC） 建置工具建置的應用程式都需要這些程式庫。 如果您的應用程式是使用這些程式庫建置的，則必須在目標系統上與應用程式一起安裝至少和建置應用程式時使用的建置工具一樣新版的 Microsoft Visual C++ 可轉散發套件。
Tags:
- msvc
- vc
- vc++
- visual-c++
- msvcp140.dll
- vcruntime140.dll
- concrt140.dll
- mfc140.dll
- visualcplusplus
- 可再發行套件
- ㄎㄜˇㄗㄞˋㄈㄚㄒㄧㄥˊㄊㄠˋㄐㄧㄢˋ
ManifestType: locale
ManifestVersion: 1.10.0
