# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.VCRedist.2015+.x64
PackageVersion: 14.50.35719.0
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/
PublisherSupportUrl: https://support.microsoft.com/
PrivacyUrl: https://privacy.microsoft.com/privacystatement
Author: Microsoft Corporation
PackageName: Microsoft Visual C++ v14 Redistributable (x64)
PackageUrl: https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist
License: Proprietary (Freeware)
LicenseUrl: https://www.microsoft.com/legal/terms-of-use
Copyright: © Microsoft Corporation
CopyrightUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks
ShortDescription: Installs runtime components of Visual C++ Libraries that are required to run 64-bit applications developed with Visual C++ ≥2015.
Description: The Microsoft Visual C++ v14 Redistributable Package (x64) installs runtime components of Visual C++ Libraries required to run 64-bit applications developed with Visual C++ 2015, 2017, 2019, 2022 or 2026 on a computer that does not have Visual C++ 2015, 2017, 2019, 2022 and/or 2026 installed.
Moniker: vcredistx64
Tags:
- msvc
- vc
- vc++
- visual-c++
- msvcp140.dll
- vcruntime140.dll
- concrt140.dll
- mfc140.dll
- visualcplusplus
ManifestType: defaultLocale
ManifestVersion: 1.10.0
