# Created with WinGet Releaser using komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: vim.vim.nightly
PackageVersion: 9.1.1976
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- diff
- gvim
- tee
- vim
- xxd
ProductCode: Vim 9.1
ReleaseDate: 2025-12-13
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.1.1976/gvim_9.1.1976_x86.exe
  InstallerSha256: ED0F465CDE11A6B4606C2FA43658B776CFD69AA1DD9C9472FA8495AEAF40D0F4
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Vim'
- Architecture: x64
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.1.1976/gvim_9.1.1976_x64.exe
  InstallerSha256: 79DAFED56FBCB91DAE5C21A39E363095C73872F817F6660CCDDB4DFBF95CAAF8
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Vim'
- Architecture: arm64
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v9.1.1976/gvim_9.1.1976_arm64.exe
  InstallerSha256: 6fb65eed6d202da383ab778efda27be9748e12f8eb1d4c9ce24a8747c45b7bb3
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Vim'
ManifestType: installer
ManifestVersion: 1.10.0
